# Generated by Django 5.1.1 on 2024-09-19 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='importan',
            new_name='important',
        ),
    ]
